create table users (
    id          bigint generated by default as identity primary key,
    login_id    varchar(255) not null,
    password    varchar(255) not null,
    name        varchar(255) not null,
    email       varchar(255),
    ui_language varchar(10),
    constraint uk_users_login_id unique (login_id),
    constraint uk_users_email unique (email)
);

create table lectures (
    id            bigint generated by default as identity primary key,
    user_id       bigint       not null,
    title         varchar(255) not null,
    subject       varchar(255),
    stt_language  varchar(255),
    status        varchar(255) not null check (status in ('RECORDING', 'COMPLETED')),
    created_at    timestamp(6),
    end_at        timestamp(6),
    duration      integer,
    files         text,
    collection_id varchar(255)
);

create table transcripts (
    id            bigint generated by default as identity primary key,
    lecture_id    bigint  not null,
    section_index integer not null,
    start_sec     integer not null,
    end_sec       integer not null,
    text          text    not null
);

create table summaries (
    id            bigint generated by default as identity primary key,
    lecture_id    bigint      not null,
    section_index integer     not null,
    start_sec     integer     not null,
    end_sec       integer     not null,
    text          text        not null,
    phase         varchar(10) not null check (phase in ('PARTIAL', 'FINAL')),
    constraint uk_summaries_lecture_section unique (lecture_id, section_index)
);

create index idx_summaries_lecture_section on summaries (lecture_id, section_index);
create index idx_summaries_lecture_start on summaries (lecture_id, start_sec);

create table qna (
    id            bigint generated by default as identity primary key,
    lecture_id    bigint       not null,
    summary_id    bigint,
    section_index integer      not null,
    card_id       varchar(128) not null,
    type          varchar(255) check (type in ('CONCEPT', 'APPLICATION', 'ADVANCED', 'COMPARISON')),
    question      varchar(255) not null,
    answer        text         not null,
    constraint uk_qna_card unique (lecture_id, section_index, card_id)
);

create table resources (
    id            bigint generated by default as identity primary key,
    lecture_id    bigint        not null,
    summary_id    bigint,
    user_id       bigint,
    card_id       varchar(128)  not null,
    section_index integer       not null,
    type          varchar(255)  not null check (type in ('PAPER', 'WIKI', 'VIDEO', 'BLOG', 'GOOGLE', 'YOUTUBE')),
    title         varchar(255)  not null,
    text          text,
    url           varchar(2048) not null,
    thumbnail     varchar(255),
    score         float(53),
    reason        text,
    detail        jsonb,
    constraint uk_resource_card unique (lecture_id, section_index, card_id)
);

create index idx_resources_summary on resources (summary_id);

create table bookmarks (
    id            bigint generated by default as identity primary key,
    user_id       bigint,
    lecture_id    bigint,
    section_index integer,
    target_type   varchar(255) check (target_type in ('RESOURCE', 'QNA')),
    target_id     bigint,
    constraint uq_bookmark_user_lecture_section_target
        unique (user_id, lecture_id, section_index, target_type, target_id)
);

create index idx_bookmarks_user_lecture on bookmarks (user_id, lecture_id);
create index idx_bookmarks_user_lecture_section on bookmarks (user_id, lecture_id, section_index);
